%{
    
    SMALLBAR-VERT for position mapping

    Make master struct for presentations of visual stimuli
    in central cx mapping experiment
   
    struct is of the form

    stim.name
    stim.num
    stim.pat_id
    stim.xpos_vec
    stim.ypos_vec
    stim.type = 'motion' or 'pos'
    stim.time
    
%}
prestim_time    = 3;
poststim_time   = 2;
motion_stim_time = 10;

%% vert off bar slow 
stim(34).name = 'smallbar_vert_off_30_dps';
stim(34).num = 34;
stim(34).pat_id = 14;
stim(34).xpos_vec = [nan(1, prestim_time*50)...
                        create_posvec(1, 92, 6, 1)...
                        create_posvec(1, 92, 6, 1)...
                        create_posvec(1, 92, 6, 1)...
                        create_posvec(1, 92, 6, 1)...                        
                        nan(1, prestim_time*50)];
                                        
stim(34).ypos_vec = [nan(1, prestim_time*50)...
                        ones(1, length(create_posvec(1, 92, 6, 1)))...
                        9*ones(1, length(create_posvec(1, 92, 6, 1)))...
                        17*ones(1, length(create_posvec(1, 92, 6, 1)))...
                        25*ones(1, length(create_posvec(1, 92, 6, 1)))...                        
                        nan(1, prestim_time*50)];
                    
stim(34).type = 'position';
stim(34).time = length(stim(34).xpos_vec)/50;

%% vert off bar medium 
stim(35).name = 'smallbar_vert_off_60_dps';
stim(35).num = 35;
stim(35).pat_id = 14;
stim(35).xpos_vec = [nan(1, prestim_time*50)...
                        create_posvec(1, 92, 3, 1)...
                        create_posvec(1, 92, 3, 1)...
                        create_posvec(1, 92, 3, 1)...
                        create_posvec(1, 92, 3, 1)...                        
                        nan(1, prestim_time*50)];
                                        
stim(35).ypos_vec = [nan(1, prestim_time*50)...
                        ones(1, length(create_posvec(1, 92, 3, 1)))...
                        9*ones(1, length(create_posvec(1, 92, 3, 1)))...
                        17*ones(1, length(create_posvec(1, 92, 3, 1)))...
                        25*ones(1, length(create_posvec(1, 92, 3, 1)))...                        
                        nan(1, prestim_time*50)];
                    
stim(35).type = 'position';
stim(35).time = length(stim(35).xpos_vec)/50;

%% vert off bar fast 
stim(36).name = 'smallbar_vert_off_180_dps';
stim(36).num = 36;
stim(36).pat_id = 14;
stim(36).xpos_vec = [nan(1, prestim_time*50)...
                        create_posvec(1, 92, 1, 1)...
                        create_posvec(1, 92, 1, 1)...
                        create_posvec(1, 92, 1, 1)...
                        create_posvec(1, 92, 1, 1)...                        
                        nan(1, prestim_time*50)];
                                        
stim(36).ypos_vec = [nan(1, prestim_time*50)...
                        ones(1, length(create_posvec(1, 92, 1, 1)))...
                        9*ones(1, length(create_posvec(1, 92, 1, 1)))...
                        17*ones(1, length(create_posvec(1, 92, 1, 1)))...
                        25*ones(1, length(create_posvec(1, 92, 1, 1)))...                        
                        nan(1, prestim_time*50)];
                    
stim(36).type = 'position';
stim(36).time = length(stim(36).xpos_vec)/50;

%% vert on bar slow 
stim(37).name = 'smallbar_vert_on_30_dps';
stim(37).num = 37;
stim(37).pat_id = 15;
stim(37).xpos_vec = [nan(1, prestim_time*50)...
                        create_posvec(1, 92, 6, 1)...
                        create_posvec(1, 92, 6, 1)...
                        create_posvec(1, 92, 6, 1)...
                        create_posvec(1, 92, 6, 1)...                        
                        nan(1, prestim_time*50)];
                                        
stim(37).ypos_vec = [nan(1, prestim_time*50)...
                        ones(1, length(create_posvec(1, 92, 6, 1)))...
                        9*ones(1, length(create_posvec(1, 92, 6, 1)))...
                        17*ones(1, length(create_posvec(1, 92, 6, 1)))...
                        25*ones(1, length(create_posvec(1, 92, 6, 1)))...                        
                        nan(1, prestim_time*50)];
                    
stim(37).type = 'position';
stim(37).time = length(stim(37).xpos_vec)/50;

%% vert on bar mediium 
stim(38).name = 'smallbar_vert_on_60_dps';
stim(38).num = 38;
stim(38).pat_id = 15;
stim(38).xpos_vec = [nan(1, prestim_time*50)...
                        create_posvec(1, 92, 3, 1)...
                        create_posvec(1, 92, 3, 1)...
                        create_posvec(1, 92, 3, 1)...
                        create_posvec(1, 92, 3, 1)...                        
                        nan(1, prestim_time*50)];
                                        
stim(38).ypos_vec = [nan(1, prestim_time*50)...
                        ones(1, length(create_posvec(1, 92, 3, 1)))...
                        9*ones(1, length(create_posvec(1, 92, 3, 1)))...
                        17*ones(1, length(create_posvec(1, 92, 3, 1)))...
                        25*ones(1, length(create_posvec(1, 92, 3, 1)))...                        
                        nan(1, prestim_time*50)];
                    
stim(38).type = 'position';
stim(38).time = length(stim(38).xpos_vec)/50;

%% vert on bar fast 
stim(39).name = 'smallbar_vert_on_180_dps';
stim(39).num = 39;
stim(39).pat_id = 15;
stim(39).xpos_vec = [nan(1, prestim_time*50)...
                        create_posvec(1, 92, 1, 1)...
                        create_posvec(1, 92, 1, 1)...
                        create_posvec(1, 92, 1, 1)...
                        create_posvec(1, 92, 1, 1)...                        
                        nan(1, prestim_time*50)];
                                        
stim(39).ypos_vec = [nan(1, prestim_time*50)...
                        ones(1, length(create_posvec(1, 92, 1, 1)))...
                        9*ones(1, length(create_posvec(1, 92, 1, 1)))...
                        17*ones(1, length(create_posvec(1, 92, 1, 1)))...
                        25*ones(1, length(create_posvec(1, 92, 1, 1)))...                        
                        nan(1, prestim_time*50)];
                    
stim(39).type = 'position';
stim(39).time = length(stim(39).xpos_vec)/50;

